# Site settings
title: Freelance Website Development
description: 'Business Card Page'
url: 'http://oanh.tran.family'
baseurl: ''
profilepic: '/images/oanh.jpg'
bkimage: '/images/bkstreet.jpg'
google_analytics: G-PMJ3E3L4TK
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Oanh Tran'
  email: thuyoanh21790@gmail.com
#  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  oanh098
  linkedin_username:  tran-oanh-620035a2
#  meetup_name: oanh098

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
exclude: ['README.md', 'screenshot-overview.png']
